#include "LevelService.h"

#include "math.h"

LevelService::LevelService(
    shared_ptr<GyroscopeService> gyroscopeService,
        shared_ptr<EngineService> engineService
#ifdef DEBUG
    ,
    shared_ptr<LogService> logService
#endif
)
{
    _gyroscopeService = gyroscopeService;
    _engineService = engineService;
#ifdef DEBUG
    _logService = logService;
#endif
}

void LevelService::setPower(float power)
{
    _power = power;
}

void LevelService::refreshState()
{
#ifdef DEBUG
    _logService->debug("refreshState requested");
#endif

    auto level = _gyroscopeService->getLevel();

#ifdef DEBUG
    _logService->debug("Current level is: x=" + String(level.getX()) + ", y=" + String(level.getY()));
    _logService->debug("Destination=" + String(_destinationRoll));
#endif

    auto xDelta = calculateDelta(level.getX(), _destinationRoll);
    auto yDelta = calculateDelta(level.getY(), _destinationPitch);

#ifdef DEBUG
    _logService->debug("Delta: roll=" + String(xDelta) + ", pitch=" + String(yDelta));
#endif
}

float LevelService::proportion(float x1, float y1, float y2)
{
    return x1 * y2 / y1;
}

float LevelService::calculateDelta(float current, float destination)
{
    return fabs(fabs(destination) - fabs(current)) * (destination > current ? 1 : -1);
}

//-------------------------------------------------------------------------------------------

// MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMWK0Odoc;,,,,,,;loxO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Oxol;,,,,,,;lodO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMWKkl,..    .......     ..;lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl;..     .......    ..;lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMW0l,.   .':lox0KKKKKKOxol;'.   .;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;.   .';loxOKKKKKK0xol;'.   .;o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMWXkc.  .,lxKNWMMMMMMMMMMMMMMWNKxc,.  .:xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOc.  .,cxKNWMMMMMMMMMMMMMMWNKxc,.  .:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMNd.   'l0WMMMMMMMMMMMMMMMMMMMMMMMWN0c.   'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx:'   .l0WMMMMMMMMMMMMMMMMMMMMMMMMW0l'   .oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMWO:  .:ONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk;   :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.  .:kXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk:.  ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMXl.  'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMXc  .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl   :x0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c   lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMXc  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl   lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.  lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMNc  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo   lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.  lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMO.  cXMMMMMMMMMMMMMMMMMMWN0O0NMMMMMMMMMMMMMMMMMMMMK;  .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  ;KMMMMMMMMMMMMMMMMMMWNKOkOOKWMMMMMMMMMMMMMMMMMMX:  .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNc  .kMMMMMMMMMMMMMMMMWXkc'. '0MMMMMMMMMMMMMMMMMMMMWd.  oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo  .xMMMMMMMMMMMMMMMMMNx;''''...,oXMMMMMMMMMMMMMMMMMx.  lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MO.  cNMMMMMMMMMMMMMMMKl,,::. '0MMMMMMMMMMMMMMMMMMMMMK;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  :XMMMMMMMMMMMMMMMMMO;;d0XNXO:  ;KMMMMMMMMMMMMMMMMX:  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// Md.  dMMMMMMMMMMMMMMMMXkOXW0' .OMMMMMMMMMMMMMMMMMMMMMWc  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.  lWMMMMMMMMMMMMMMMMMWXWMMMMMMK; .xMMMMMMMMMMMMMMMMWo  .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// Md   dMMMMMMMMMMMMMMMMMMMMM0' 'OMMMMMMMMMMMMMMMMMMMMMWc  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMMMMMMMMMMMMMMMMMMMMMMMMM0, .xMMMMMMMMMMMMMMMMWo  .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0XWMMMMMMMMMMMMMMMMM
// Md.  oMMMMMMMMMMMMMMMMMMMMM0' .OMMMMMMMMMMMMMMMMMMMMMWc  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMMMMMMMMMMMMMMMMMMMMMMMMNl  cXMMMMMMMMMMMMMMMMWo  .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;..dNMMMMMMMMMMMMMMMM
// MK,  ,KMMMMMMMMMMMMMMMMMMMM0' .OMMMMMMMMMMMMMMMMMMMMMO.  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  '0MMMMMMMMMMMMMMMMMMMMMMMMK:..lXMMMMMMMMMMMMMMMMM0,  ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMWl   '0MMMMMMMMMMMMMMMM
// MWl  .dWMMMMMMMMMMMMMMMMMMM0' .OMMMMMMMMMMMMMMMMMMMMNl  .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   oNMMMMMMMMMMMMMMMMMMMMMXd'.:0WMMMMMMMMMMMMMMMMMNo.  oWMMMMMMMMMMMMMMMMMMMMMMMMMMMX:   .kWMMMMMMMMMMMMMMM
// MMO'  'OMMMMMMMMMMMMMMMMMMM0' .OMMMMMMMMMMMMMMMMMMMWx.  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  .kWMMMMMMMMMMMMMMMMMMXd'.c0WMMMMMMMMMMMMMMMMMMWk.  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMk.    cNMMMMMMMMMMMMMMM
// MMWx.  ,0MMMMMMMMMMMMMMMMMM0' 'OMMMMMMMMMMMMMMMMMMWO.  .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'  'OMMMMMMMMMMMMMMMMXd'.cOWMMMMMMMMMMMMMMMMMMMM0'  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     '0MMMMMMMMMMMMMMM
// MMMWk.  ;0MMMMMMMMMMMMNkdddc. .cddxKMMMMMMMMMMMMMWO'  .xNMMW0dddddddddddddddddddddddddddONMMMWO'  'OWWMMMMMMMMMMMNx'  ;odddddddONMMMMMMMMMMMWO,  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'      oWMMMMMMMMMMMMMM
// MMMMWx.  .dXMMMMMMMMMMKl,,,,,,,,,,;kMMMMMMMMMMMMKl.  'OMMMMN:                           ,KMMMMWk.  .;oXMMMMMMMMMMXl,,,,,,,,,,,,lKMMMMMMMMMMXo.  .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  ..  cXMMMMMMMMMMMMMM
// MMMMMWO:.  :0WMMMMMMMMMWWWWWWWWWWWWMMMMMMMMMMMWO,  .c0WMMMMN:  .:lllllllllllllllllllc.  ,KMMMMMW0c.   ;OWMMMMMMMMMWWWWWWWWWWWWWWMMMMMMMMMWO;  .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  .dc  .kMMMMMMMMMMMMMM
// MMMMMMMNd.  .:xKMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.  .xWMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMNx.   .:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  ,0o   oNMMMMMMMMMMMMM
// MMMMMMMMWKl.   .lkXWMMMMMMMMMMMMMMMMMMMMWKkc.   'oKWMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMWKko'   .lkKWMMMMMMMMMMMMMMMMMMMMWKkl.   .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo  .dW0,  ,KMMMMMMMMMMMMM
// MMMMMMMMMMWXk:.   .;ox0XNWMMMMMMMWWNXOxl,.   .cOXWMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMWXOc.   .;lxOXNWWMMMMMMMWNXOxo;.   .cOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .xMXc  .OWMMMMMMMMMMMM
// MMMMMMMMMMMMMWKxc,.    .',cllllllc,'.     'lxKWMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMWKxl,.    .',cllllllc,'.     'cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  :XMMk.  cWMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMNKxl:'...         ..':lxOXMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMWKxl:'...         ..':lxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.  oWMM0'  ,0MMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMWNXX0xdddddddOKXNMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMNXX0kdddddddkKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  ,0MMMWo   dMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.  ;XMMMMk.  lNMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc  .xWMMMMN:  .OMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  '0MMMMMNl  .dWMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.  oWMMMMMMO'  ;XMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl  .xMMMMMMMX:  'OMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.  ;KMMMMMMMMk.  lWMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  lWMMMMMMMMO.  ;KMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  'OMMMMMMMMMNl  .xMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  .xXWMMMMMWN0:   oWMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl     .:OWMMXo'.    '0MMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l::'   lWMMO.  .;::oXMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMWWX0OxllllllldO0XWWMMMMMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMMMMMWWN0OxolllllldO0KWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMNKkl;,..            .,,cx0NMMMMMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMMMMWKkl;,..            .,,cdONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMMMWKxl,.   ..;;cdddddddl:;'.   .'cd0WMMMMMMMMMMMN:  '0MMMMMMMMMMMMMMMMMMMX;  ,KMMMMMMMMMMMMMMMXkl,.   ..,;cdddddddo:;'.    'cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMMMWKo.   .;lk0XWMMMMMMMMMMMMNKko:.   .ckXMMMMMMMMMN:  .ONNNNNNNNNNNNNNNNNNN0,  ,KMMMMMMMMMMMMWKd'   .,cx0XWMMMMMMMMMMMMNKOd:.   .:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMMNx;.  .:xKWMMMMMMMMMMMMMMMMMMMMMWXOl.   .oKWMMMMMMN:   .'''''''''''''''''''.   ,KMMMMMMMMMNXk:.  .;xKWMMMMMMMMMMMMMMMMMMMMMWXOl.   .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMMMKc.  ,d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.  'kWMMMMMNl...........................:KMMMMMMMMXl'.  'o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc.  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMMXo.  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,  .cKMMMMMNKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMMMMMMNd'   .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;  .:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMMXc  .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.  .;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo.  'OWMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMMXc  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.  l0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO.  ,OWMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMMXc  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.  lXMMMMMMMMMMMMMMMMMMMW0dddkNMMMMMMMMMMMMMMMMWk'  'OMMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMWx.  cNMMMMMMMMMMMMMMMMXkdl:::cd0NMMMMMMMMMMMMMMMMWd.  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO.  :XMMMMMMMMMMMMMMMMMMMWx.   .OMMMMMMMMMMMMMMMMMWx.  :XMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MMX:  'OMMMMMMMMMMMMMMMWx'.,cll:'..:OWMMMMMMMMMMMMMMMX;  .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc  .kWMMMMMMMMMMMMMMMMMMXo..:. .OMMMMMMMMMMMMMMMMMMNc  .xMMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MWx.  lNMMMMMMMMMMMMMMMWko0NMMMWNd. ,KMMMMMMMMMMMMMMMWx. .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.  cXMMMMMMMMMMMMMMMMMWK:.'O0, .OMMMMMMMMMMMMMMMMMMMk.  cNMMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MNc  .OMMMMMMMMMMMMMMMMMMMMMMMMMWk. ;KMMMMMMMMMMMMMMMMK,  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl  .xMMMMMMMMMMMMMMMMMMO' ;0WK, .OMMMMMMMMMMMMMMMMMMMX;  '0MMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MWc  .OMMMMMMMMMMMMMMMMMMWNNNNXOl'.,OWMMMMMMMMMMMMMMMMK,  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl  .xMMMMMMMMMMMMMMMMNk'.cXMMK, .OMMMMMMMMMMMMMMMMMMMX:  '0MMMMMMMMMMMMMMMMMMMMMMMk.  lWMMO.  cNMMMMMMMMMMMM
// MWc  .OMMMMMMMMMMMMMMMMMM0:'''.  .:0WMMMMMMMMMMMMMMMMMK,  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl  .xMMMMMMMMMMMMMMMWd..xNMMMK, .OMMMMMMMMMMMMMMMMMMMX:  '0MMMMMMMMMMMMMMMMMMMMMMMk.  cNWWk.  cNMMMMMMMMMMMM
// MWx. .oNMMMMMMMMMMMMMMMMMN0kkkkdc'.'dNMMMMMMMMMMMMMMMWk.  lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  lNMMMMMMMMMMMMMXl. c0KKKKx' .dKXWMMMMMMMMMMMMMMMMO.  cXMMMMMMMMMMMMMMMMMMMMMMMk.  .',,.   cNMMMMMMMMMMMM
// MMK,  '0MMMMMMMMMMMMMMMMMMMMMMMMWK: .dWMMMMMMMMMMMMMMN:  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  .OMMMMMMMMMMMMMO,..''''''.   .'cKMMMMMMMMMMMMMMMNl  .xMMMMMMMMMMMMMMMMMMMMMMMMK:..........xWMMMMMMMMMMMM
// MMNo.  lNMMMMMMMMMMMMMMMMMMMMMMMMWo  cWMMMMMMMMMMMMMMx.  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.  cNMMMMMMMMMMMMWXKKKKKKKKx. .dKXWMMMMMMMMMMMMMMMk.  ;KMMMMMMMMMMMMMMMMMMMMMMMMMNKKKKKKKKKXWMMMMMMMMMMMMM
// MMMX:  .dNMMMMMMMMMMMMM0dk0XWWWWKo. ;0MMMMMMMMMMMMMWO'  'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .oNMMMMMMMMMMMMMMMMMMMMMK, .OMMMMMMMMMMMMMMMMM0,  .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMK;  .dWMMMMMMMMMMMMO;...,,,,'.,dXMMMMMMMMMMMMMMO'  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .oKNMMMMMMMMMMMMMMMMMMMXdcoXMMMMMMMMMMMMMMMM0,  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMK:  .lKWMMMMMMMMMMMNXOxdddxOXNMMMMMMMMMMMMMMXd.  'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .'c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'  .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMKl.  'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;   ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.   .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:   ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMWk'  .:kXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOl.  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,   .;xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo.  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMWKo.   .l0NMMMMMMMMMMMMMMMMMMMMMMMNKd'   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOd'   .cONWMMMMMMMMMMMMMMMMMMMMMMWKx,   .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMWKx:.  .'cd0XNMMMMMMMMMMMMMWNKxl,.   ;d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkc.   ':o0XNMMMMMMMMMMMMMWNKkl,.   ,o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMW0o:.   ..,ccdkOOOOOOdlc;..   .;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d:.    .,:cokOOOOOOxlc;..   .,lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMWXOo;'.               ..;cdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOd:'.               ..,co0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMWNKOxxoc:::::::oxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOxxoc:::::::oxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM